repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.56.0'
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint@4.15.0
        -   typescript@latest
        -   eslint-plugin-react@6.10.3
        files: '.tsx?'
        types: [file]
