name = "wordable-worker"
main = "src/index.ts"
compatibility_date = "2024-04-15"


compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "KV", id = "dd8f44886d33435d9829f56ef5ee8b88" }, # test
    # { binding = "KV", id= "8728bded08c548ea97aa7520e6f7c256" }, # prod
]
